version: '3.8'

services:
  # 生产环境服务
  lazybala:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDTIME: ${BUILDTIME:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
        VERSION: ${VERSION:-latest}
        PUID: ${PUID:-1001}
        PGID: ${PGID:-1001}
    image: lazybala:latest
    container_name: lazybala
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 数据持久化目录
      - ./data/audiobooks:/app/audiobooks
      - ./data/config:/app/config
      - ./data/cookies:/app/cookies
      # 注意：移除 bin 目录挂载，yt-dlp 保持在容器内
      # - ./data/bin:/app/bin
    environment:
      - PORT=8080
      - GIN_MODE=release
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - lazybala-network
    labels:
      - "com.docker.compose.project=lazybala"
      - "com.docker.compose.service=lazybala"
      - "traefik.enable=true"
      - "traefik.http.routers.lazybala.rule=Host(`lazybala.local`)"
      - "traefik.http.services.lazybala.loadbalancer.server.port=8080"

  # 开发环境服务
  lazybala-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: lazybala:dev
    container_name: lazybala-dev
    ports:
      - "8081:8080"
    volumes:
      # 源代码挂载（热重载）
      - .:/app
      - /app/tmp
      # 数据持久化目录
      - ./data/audiobooks:/app/audiobooks
      - ./data/config:/app/config
      - ./data/cookies:/app/cookies
      # 注意：开发环境也移除 bin 目录挂载
      # - ./data/bin:/app/bin
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - TZ=Asia/Shanghai
    networks:
      - lazybala-network
    profiles:
      - dev

networks:
  lazybala-network:
    driver: bridge

volumes:
  audiobooks:
    driver: local
  config:
    driver: local
  cookies:
    driver: local
  # 移除 bin 卷定义，yt-dlp 保持在容器内
  # bin:
  #   driver: local
